export const mockClassmates = [
  {
    id: 1,
    name: "Austin Burris",
    maiden_name: null,
    city: "Dallas, TX",
    occupation: "Software Engineer & Entrepreneur",
    family: "Single",
    linkedin: "https://linkedin.com",
    instagram: "https://instagram.com",
    fun_fact: "Built 10+ apps since graduation",
    initials: "AB",
    color: "#C8102E",
  },
  {
    id: 2,
    name: "Marcus Johnson",
    maiden_name: null,
    city: "Atlanta, GA",
    occupation: "Business Owner",
    family: "Married, 3 kids",
    linkedin: null,
    instagram: "https://instagram.com",
    fun_fact: "Opened his own barbershop at 28",
    initials: "MJ",
    color: "#1a6b3c",
  },
  {
    id: 3,
    name: "Destiny Williams",
    maiden_name: "Williams",
    city: "Indianapolis, IN",
    occupation: "Nurse Practitioner",
    family: "Married, 2 kids",
    linkedin: "https://linkedin.com",
    instagram: null,
    fun_fact: "Ran her first marathon in 2022",
    initials: "DW",
    color: "#7b3fa0",
  },
  {
    id: 4,
    name: "DeShawn Mitchell",
    maiden_name: null,
    city: "Chicago, IL",
    occupation: "High School Coach & Teacher",
    family: "Married, 1 kid",
    linkedin: null,
    instagram: "https://instagram.com",
    fun_fact: "Took his team to state finals two years running",
    initials: "DM",
    color: "#1a5c8b",
  },
  {
    id: 5,
    name: "Jasmine Carter",
    maiden_name: "Reynolds",
    city: "Charlotte, NC",
    occupation: "Real Estate Agent",
    family: "Married, 2 kids",
    linkedin: "https://linkedin.com",
    instagram: "https://instagram.com",
    fun_fact: "Sold over $10M in real estate last year",
    initials: "JC",
    color: "#b85c1a",
  },
  {
    id: 6,
    name: "Kevin Thomas",
    maiden_name: null,
    city: "Los Angeles, CA",
    occupation: "Music Producer",
    family: "Single",
    linkedin: null,
    instagram: "https://instagram.com",
    fun_fact: "Has worked with Grammy-nominated artists",
    initials: "KT",
    color: "#8b1a6b",
  },
  {
    id: 7,
    name: "Brianna Davis",
    maiden_name: "Davis",
    city: "Indianapolis, IN",
    occupation: "Elementary School Principal",
    family: "Married, 4 kids",
    linkedin: "https://linkedin.com",
    instagram: null,
    fun_fact: "Named Indiana Educator of the Year 2024",
    initials: "BD",
    color: "#1a8b6b",
  },
  {
    id: 8,
    name: "Jordan Banks",
    maiden_name: null,
    city: "Houston, TX",
    occupation: "US Army Officer",
    family: "Married, 2 kids",
    linkedin: null,
    instagram: null,
    fun_fact: "Served three overseas deployments",
    initials: "JB",
    color: "#3d6b1a",
  },
  {
    id: 9,
    name: "Tiffany Moore",
    maiden_name: "Johnson",
    city: "Columbus, OH",
    occupation: "Pediatric Dentist",
    family: "Married, 1 kid",
    linkedin: "https://linkedin.com",
    instagram: "https://instagram.com",
    fun_fact: "Started a free dental clinic for underserved kids",
    initials: "TM",
    color: "#6b4a1a",
  },
  {
    id: 10,
    name: "Chris Wallace",
    maiden_name: null,
    city: "Detroit, MI",
    occupation: "Pastor & Community Leader",
    family: "Married, 3 kids",
    linkedin: null,
    instagram: "https://instagram.com",
    fun_fact: "Leads a congregation of 2,000+ members",
    initials: "CW",
    color: "#1a3d8b",
  },
  {
    id: 11,
    name: "Nicole Harris",
    maiden_name: "Harris",
    city: "Memphis, TN",
    occupation: "Attorney",
    family: "Single",
    linkedin: "https://linkedin.com",
    instagram: "https://instagram.com",
    fun_fact: "Graduated top of her law school class",
    initials: "NH",
    color: "#8b1a1a",
  },
  {
    id: 12,
    name: "Tyler Brooks",
    maiden_name: null,
    city: "Phoenix, AZ",
    occupation: "Software Engineer",
    family: "Married, no kids yet",
    linkedin: "https://linkedin.com",
    instagram: null,
    fun_fact: "Works remotely and has visited 40+ countries",
    initials: "TB",
    color: "#2d4a8b",
  },
];

export const mapMarkers = [
  { name: "Austin Burris", city: "Dallas, TX", coordinates: [-96.7970, 32.7767], count: 2 },
  { name: "Marcus J.", city: "Atlanta, GA", coordinates: [-84.3880, 33.7490], count: 1 },
  { name: "Destiny W.", city: "Indianapolis, IN", coordinates: [-86.1581, 39.7684], count: 3 },
  { name: "DeShawn M.", city: "Chicago, IL", coordinates: [-87.6298, 41.8781], count: 2 },
  { name: "Jasmine C.", city: "Charlotte, NC", coordinates: [-80.8431, 35.2271], count: 1 },
  { name: "Kevin T.", city: "Los Angeles, CA", coordinates: [-118.2437, 34.0522], count: 2 },
  { name: "Jordan B.", city: "Houston, TX", coordinates: [-95.3698, 29.7604], count: 1 },
  { name: "Tiffany M.", city: "Columbus, OH", coordinates: [-82.9988, 39.9612], count: 2 },
  { name: "Chris W.", city: "Detroit, MI", coordinates: [-83.0458, 42.3314], count: 1 },
  { name: "Nicole H.", city: "Memphis, TN", coordinates: [-90.0490, 35.1495], count: 1 },
  { name: "Tyler B.", city: "Phoenix, AZ", coordinates: [-112.0740, 33.4484], count: 1 },
  { name: "Classmates", city: "New York, NY", coordinates: [-74.0060, 40.7128], count: 3 },
  { name: "Classmates", city: "Washington, DC", coordinates: [-77.0369, 38.9072], count: 2 },
];

export const timeCapsule = [
  { label: "Gas Price", value: "$2.80/gal", icon: "⛽" },
  { label: "iPhone", value: "Not Released Yet", icon: "📵" },
  { label: "#1 Movie", value: "Spider-Man 3", icon: "🕷️" },
  { label: "#1 Song", value: "Umbrella — Rihanna", icon: "🎵" },
  { label: "Facebook", value: "College Students Only", icon: "📘" },
  { label: "Twitter", value: "Just Launched", icon: "🐦" },
  { label: "YouTube", value: "Only 2 Years Old", icon: "▶️" },
  { label: "Average Home", value: "$247,000", icon: "🏠" },
];

export const playlist = [
  { id: 1, title: "Umbrella", artist: "Rihanna", year: 2007 },
  { id: 2, title: "Gold Digger", artist: "Kanye West", year: 2005 },
  { id: 3, title: "Buy U A Drank", artist: "T-Pain ft. Yung Joc", year: 2007 },
  { id: 4, title: "Because of You", artist: "Ne-Yo", year: 2007 },
  { id: 5, title: "Kiss Kiss", artist: "Chris Brown ft. T-Pain", year: 2007 },
  { id: 6, title: "Lollipop", artist: "Lil Wayne", year: 2008 },
  { id: 7, title: "No One", artist: "Alicia Keys", year: 2007 },
  { id: 8, title: "Ordinary People", artist: "John Legend", year: 2004 },
  { id: 9, title: "Stronger", artist: "Kanye West", year: 2007 },
  { id: 10, title: "SexyBack", artist: "Justin Timberlake", year: 2006 },
  { id: 11, title: "Yeah!", artist: "Usher ft. Lil Jon", year: 2004 },
  { id: 12, title: "In Da Club", artist: "50 Cent", year: 2003 },
  { id: 13, title: "Crank That", artist: "Soulja Boy Tell 'Em", year: 2007 },
  { id: 14, title: "Beautiful Girls", artist: "Sean Kingston", year: 2007 },
  { id: 15, title: "The Way I Are", artist: "Timbaland ft. Keri Hilson", year: 2007 },
  { id: 16, title: "Crazy In Love", artist: "Beyoncé ft. Jay-Z", year: 2003 },
  { id: 17, title: "A Milli", artist: "Lil Wayne", year: 2008 },
  { id: 18, title: "Goodies", artist: "Ciara", year: 2004 },
];

export const superlatives = [
  { id: 1, title: "Most Likely to Succeed", icon: "🏆", description: "The one we all knew was going places", nominees: [] },
  { id: 2, title: "Class Clown", icon: "😂", description: "Had the whole hallway in tears — the good kind", nominees: [] },
  { id: 3, title: "Best Dressed", icon: "👔", description: "Always fresh, always fly", nominees: [] },
  { id: 4, title: "Most Athletic", icon: "⚡", description: "Dominated every sport they touched", nominees: [] },
  { id: 5, title: "Most Changed", icon: "🦋", description: "The glow-up is REAL", nominees: [] },
  { id: 6, title: "Most Likely to Be Famous", icon: "⭐", description: "We're waiting for the album / movie / news segment", nominees: [] },
];

export const hallOfRaiders = [
  {
    id: 1,
    name: "Austin Burris",
    category: "Technology",
    tagline: "Building software, one startup at a time.",
    description: "Software engineer turned entrepreneur based in Dallas, TX. Building apps that solve real problems.",
    initials: "AB",
    color: "#C8102E",
  },
  {
    id: 2,
    name: "Brianna Davis",
    category: "Education",
    tagline: "Indiana Educator of the Year 2024.",
    description: "Started as a classroom teacher, now leading a school as Principal. Shaping the next generation.",
    initials: "BD",
    color: "#1a8b6b",
  },
  {
    id: 3,
    name: "Jordan Banks",
    category: "Military",
    tagline: "Serving with honor and distinction.",
    description: "US Army Officer with three overseas deployments. Protecting freedom every single day.",
    initials: "JB",
    color: "#3d6b1a",
  },
  {
    id: 4,
    name: "Chris Wallace",
    category: "Ministry",
    tagline: "Leading a congregation of 2,000+ in Detroit.",
    description: "Pastor, community leader, and father. Building something bigger than himself.",
    initials: "CW",
    color: "#1a3d8b",
  },
  {
    id: 5,
    name: "Tiffany Moore",
    category: "Healthcare",
    tagline: "Free dental care for kids who need it most.",
    description: "Pediatric dentist who started a pro bono clinic serving underserved children in Columbus, OH.",
    initials: "TM",
    color: "#6b4a1a",
  },
  {
    id: 6,
    name: "Kevin Thomas",
    category: "Entertainment",
    tagline: "Producing beats, chasing Grammy gold.",
    description: "Music producer in LA working with Grammy-nominated artists. Living the dream he had in class.",
    initials: "KT",
    color: "#8b1a6b",
  },
];

export const memoryCategories = ['All', 'Sports', 'Homecoming', 'Prom', 'Spirit Week', 'Senior Trip', 'Graduation'];

export const mockMemories = [
  { id: 1, category: 'Sports', title: 'Football Season 2006', caption: 'Raider pride on the field', gradient: 'linear-gradient(135deg, #C8102E 0%, #111 100%)' },
  { id: 2, category: 'Homecoming', title: 'Homecoming 2005', caption: 'The court that started it all', gradient: 'linear-gradient(135deg, #C9A44A 0%, #8B0000 100%)' },
  { id: 3, category: 'Prom', title: 'Prom Night 2007', caption: 'We cleaned up nice', gradient: 'linear-gradient(135deg, #1a1a2e 0%, #C8102E 100%)' },
  { id: 4, category: 'Spirit Week', title: 'Spirit Week 2006', caption: 'Red day was our day', gradient: 'linear-gradient(135deg, #8B0000 0%, #C8102E 60%, #222 100%)' },
  { id: 5, category: 'Graduation', title: 'Graduation Day 2007', caption: 'The day that changed everything', gradient: 'linear-gradient(135deg, #C9A44A 0%, #111 100%)' },
  { id: 6, category: 'Sports', title: 'Basketball Season 2007', caption: 'Raiders on the hardwood', gradient: 'linear-gradient(135deg, #C8102E 0%, #2d1a1a 100%)' },
  { id: 7, category: 'Senior Trip', title: 'Senior Trip 2007', caption: 'The memories we made', gradient: 'linear-gradient(135deg, #1a4a8b 0%, #0a2a4a 100%)' },
  { id: 8, category: 'Homecoming', title: 'Homecoming 2006', caption: 'Last homecoming as Raiders', gradient: 'linear-gradient(135deg, #C9A44A 0%, #4a2a00 100%)' },
  { id: 9, category: 'Spirit Week', title: 'Class Day 2006', caption: 'Seniors vs. everyone', gradient: 'linear-gradient(135deg, #222 0%, #C8102E 100%)' },
  { id: 10, category: 'Graduation', title: 'Senior Banquet 2007', caption: 'One final night together', gradient: 'linear-gradient(135deg, #8B0000 0%, #C9A44A 100%)' },
  { id: 11, category: 'Sports', title: 'Track & Field 2006', caption: 'Running for Ritter', gradient: 'linear-gradient(135deg, #2d1a1a 0%, #C8102E 80%, #111 100%)' },
  { id: 12, category: 'Prom', title: 'Prom Pre-Game 2007', caption: 'Getting ready together', gradient: 'linear-gradient(135deg, #1a1a1a 0%, #8b1a6b 100%)' },
];

export const inMemoriam = [];

export const reunionSchedule = [
  {
    day: "Friday",
    date: "July 18, 2027",
    events: [
      { time: "6:00 PM", title: "Welcome Mixer", location: "TBD Venue, Indianapolis", description: "Reconnect, grab a drink, and get the weekend started right. Casual dress." },
      { time: "8:00 PM", title: "Late Night Hangout", location: "Same Venue", description: "Keep the energy going. Old playlists, old friends." },
    ]
  },
  {
    day: "Saturday",
    date: "July 19, 2027",
    events: [
      { time: "10:00 AM", title: "Campus Tour", location: "Cardinal Ritter High School", description: "Walk the halls again. See what's changed. Remember what hasn't." },
      { time: "12:00 PM", title: "Cookout & Family Time", location: "TBD Park", description: "Families welcome. Kids, food, music, and memories." },
      { time: "7:00 PM", title: "Class Reunion Gala", location: "TBD Ballroom", description: "The main event. Dress to impress. Dinner, dancing, awards, and the class slide show." },
      { time: "10:00 PM", title: "After-Party", location: "TBD", description: "For the real ones who aren't ready for the night to end." },
    ]
  },
  {
    day: "Sunday",
    date: "July 20, 2027",
    events: [
      { time: "10:00 AM", title: "Sunday Brunch", location: "TBD Restaurant", description: "Relaxed, low-key, recovery mode. Final goodbyes and last laughs." },
      { time: "12:00 PM", title: "Farewell", location: "See You in 5 Years", description: "Until next time, Raiders." },
    ]
  },
];
